### ISSUE TITLE
Include constants for new syscalls

### ISSUE THREAD

**Issue by FauxFaux** [japaric/syscall.rs#12]
In linux HEAD, there are a number of new syscalls (including `copy_file_range`, the one I am interested in), which are not exposed. Please add constants for them:
https://github.com/torvalds/linux/blob/master/include/uapi/asm-generic/unistd.h#L707

**Comment by tbu-** [comment]
Please link to exact revisions so the links don't get outdated. I think the current one already is. If you press `y` on any Github page, you'll get a permanent link like this: https://github.com/torvalds/linux/blob/00ea1ceebe0d9f2dc1cc2b7bd575a00100c27869/include/uapi/asm-generic/unistd.h#L721

**Comment by FauxFaux** [comment]
My link was to the last included syscall (i.e. everything below this point needs to be added), but point taken, and thanks for the `y` hint.

**Comment by japaric** [comment]
> In linux HEAD

I don't think we should expose syscall that haven't made to a stable release as they may change or not make it to stable.

We'll have to update the NR generation method as the current one is not extensive (it doesn't generate all the syscall numbers) and gets the syscall numbers from a relatively old kernel version (4.4, I think)

The new generation method should download the source of the latest stable kernel and extract the syscall numbers from it.

**Comment by tbu-** [comment]
`copy_file_range` in particular seems to be older, I have a manpage about this syscall on my system that says that it was introduced in Linux 4.5.

**Comment by tbu-** [comment]
(i.e. it is in stable already).
